############################################Telegram设置##################################
# bot token
bot_token: 7788520866:AAH1tq-0NCSMfgZeh8VrHYJUwldsmPgq71w
# bot_name
bot_name: "@yhfw_115_bot"
# 授权可以使用该bot的user_id
allowed_user: 1012138188
# telegram 的api信息地址(转存视频文件时需要)
tg_api_id: 14334744
tg_api_hash: e5dc45cda4d4f5ebe7d2d612efb62b1c
############################################115开放平台##################################
115_app_id: 100197559
#############################################115离线设置###################################
# 下载完成后自动删除文件夹中的广告文件
clean_policy:
  # 是否开启自动清理 on: 开启 off: 关闭
  # 当设置为off时，所有策略不会生效，默认为开启
  switch: "on"
  # 文件小于设置值则自动删除单位K,M,G
  less_than: 900M

# 115离线文件夹
offline_path: /云下载

# 设置分类文件夹
# 离线下载完成后，会弹出需要移动到的分类文件夹，可以设置多个
# "name"为分类目录设置别名，"path" 115上的完整路径
category_folder:
  # 电影下的分类目录
  - name: movies
    display_name: 电影
    path_map:
      - name: 外语电影
        path: /影视/电影/外语电影
      - name: 华语电影
        path: /影视/电影/华语电影
      - name: 动画电影
        path: /影视/电影/动画电影
      - name: ForLei影视
        path: /影视/电影/ForLei
  # 剧集下的分类
  - name: series
    display_name: 剧集
    path_map:
      - name: 美剧
        path: /影视/剧集/美剧
      - name: 国产剧
        path: /影视/剧集/国产
      - name: ForLei剧集
        path: /影视/剧集/ForLei
      - name: 综艺
        path: /影视/综艺
  # AV
  - name: av
    display_name: AV
    path_map:
      - name: 步兵精品
        path: /AV/步兵精品
      - name: JAV图书馆
        path: /AV/JAV图书馆
      - name: 无码流出
        path: /AV/OutFlow
      - name: 国产直播
        path: /AV/国产直播精选 

# 订阅会在指定路径自动创建以演员命名的文件夹
subscribe:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
  javdb_cookie: "receive-cookie-deprecation=1; yandexuid=7653175931733840681; yuidss=7653175931733840681; i=dKFhyIGRvtophNXFpFogbhdwI4jYHQLn9hhE0zerL7MoRVR6fFKdfw14fFwdFhZTKFCsit5i5ITDSqE/s4sbtHfrGMw=; yashr=614322771734011119; sync_cookie_csrf=4261090947fake; yp=1747919581.yu.7653175931733840681; ymex=1750425181.oyu.7653175931733840681#1765547100.yrts.1734011100#1765547100.yrtsi.1734011100; sync_cookie_ok=synced; yabs-sid=1344203521747833181; bh=EkEiQ2hyb21pdW0iO3Y9IjEzNiIsICJHb29nbGUgQ2hyb21lIjt2PSIxMzYiLCAiTm90LkEvQnJhbmQiO3Y9Ijk5IhoDeDg2Ig0xMzYuMC43MTAzLjkzKgI/MDoJIldpbmRvd3MiQgYxOS4wLjBKAjY0UlkiQ2hyb21pdW0iO3Y9IjEzNi4wLjcxMDMuOTMiLCJHb29nbGUgQ2hyb21lIjt2PSIxMzYuMC43MTAzLjkzIiwiTm90LkEvQnJhbmQiO3Y9Ijk5LjAuMC4wImDdorfBBmoe3Mrh/wiS2KGxA5/P4eoD+/rw5w3r//32D8GjzYcI"
  path: /AV/女优
  # 订阅权重 设置高清，字幕的分数，订阅时会自动订阅得分最高的磁力
  sub_weight:
    # 高清
    hd: 5
    # 字幕
    subtitle_zh: 3

#############################################软链接设置####################################
# 是否创建软链（非302）
create_strm: True
# CloudDrive2 挂载115的根目录
mount_root: /CloudNAS/115
# 软链接根目录，软链接目录可以看成是115挂载目录的镜像
strm_root: /media/115

#############################################EMBY设置####################################
# EmbyServer地址 格式 http(s)://ip(域名):端口
emby_server: http://192.168.1.145:8096
# Emby APIkey  Emby-->API秘钥-->新建
api_key: 647e5f52c98943299f04df91d7822af2

#############################################电影订阅####################################
# 自动订阅https://nullbr.online/上的资源，有满足要求的自动离线到115
# 自动订阅需要申请app_id，参考申请方法
# https://nullbr.online/api?title=00.%F0%9F%93%A3api%E5%BC%80%E6%94%BE%E8%AE%A1%E5%88%92
x_app_id: yYcjwJRq0
x_api_key: DO2c8f7zYj21WFiWZcK32iLF8ZVlkePg
# 订阅条件，全部满足才订阅
sub_condition:
  # 包含中字
  zh_cn: true
  # Dolby Vision
  dolby_vision: false
  # 分辨率优先级
  resolution_priority:
    - 2160
    - 1080